version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/contracts
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            yarn
            yarn truffle install
      - run:
          name: compile
          command: yarn truffle compile
      - run:
          name: test
          command: yarn run eslint .
          command: yarn run solium -- --dir ./contracts

          # for truffle test
          command: sed -i '5i mocha:{reporter:"mocha-junit-reporter"},' truffle.js

          command: yarn test
      - store_artifacts:
        - path: ./test-results.xml
